apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-frontend
  name: app-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: afangndong/app-frontend:latest
        resources: {}
status: {}
---
apiVersion: v1 
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 50000
  selector:
    app: calculator
